name: CI Workflow

on:
  push:
    branches:
      - main
      - release
      - tests
  pull_request:
    branches:
      - master
      - release
      - develop
      - tests

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Козаков Антон" 
      GROUP: "M3111"            

    steps:
      # 1. Шаг: Вывод ФИО, номера группы и ника на GitHub
      - name: Display User Information
        run: |
          echo "Full Name: ${{ env.FULL_NAME }}"
          echo "Group: ${{ env.GROUP }}"
          echo "GitHub Username: ${{ github.actor }}" 

      # 2. Шаг: Установка Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 5. Шаг: Проверка стиля кода с помощью flake8
      - name: Check code style with flake8
        run: |
          pip install flake8
          flake8 --max-line-length=79 
